services:
  - type: web
    name: django-todo-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn backend.wsgi --workers 3 --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        fromDatabase: false
      - key: DATABASE_URL
        fromDatabase: false
      - key: ALLOWED_HOSTS
        fromDatabase: false
      - key: DEBUG
        fromDatabase: false
